object_names:
  - "dingo2"
  - "mug1"
object_msg_types: # "geometry_msgs/{PoseStamped,TransformStamped,PoseWithCovarianceStamped}"
  - "geometry_msgs/PoseStamped"
  - "geometry_msgs/PoseStamped"
object_frame_ids:
  - "map"
  - "map"
object_frequency_divider:
  - 2
  - 2
object_publish_topics:
  - "/vicon/dingo2"
  - "/vicon/mug1"

