object_names:
  - "dingo1"
object_msg_types: # "geometry_msgs/{PoseStamped,TransformStamped,PoseWithCovarianceStamped}"
  - "geometry_msgs/PoseStamped"
object_frame_ids:
  - "map"
object_frequency_divider:
  - 2
object_publish_topics:
  - "/vicon/dingo1"

